= Vert.x Spring-vertx Distributed Task Queue

This project is a demo of producer consumer pattern via vert.x verticles and vert.x cluster. A producer program keeps a list of task and worker programs
keep sending request for task to be assigned. When workers finishes processing task it requests for another one.
Any number of instances of workers can be created.

Note that because workers are doing blocking  assuming task processing will take lot of time,
 the processing happens within an executeBlocking call, to
avoid blocking the event bus.

You can run it directly in your IDE by creating a run configuration that uses the main class
`io.vertx.examples.spring.DistributedTaskProcessor`.

The pom.xml uses the Maven shade plugin to assemble the application and all it's dependencies into a single "fat" jar.

To build a "fat jar"

    mvn package

To run the fat jar:

    java -jar target/vertx-distributed-task-processor-1.0.jar

(You can take that jar and run it anywhere there is a Java 8+ JDK. It contains all the dependencies it needs so you
don't need to install Vert.x on the target machine).
